[package]
name = "subkey"
version = "0.1.0"
authors = ["Edwin Wang <lark930@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
sp-core = { version = "2.0.0-alpha.3", git = "https://github.com/paritytech/substrate" }
node-runtime = { version = "*", path = "../../node/runtime" }
node-primitives = { version = "*", path = "../../node/primitives" }
sp-runtime = { version = "2.0.0-alpha.3", git = "https://github.com/paritytech/substrate" }
rand = "0.7.3"
clap = "2.33.0"
tiny-bip39 = "0.7.1"
rustc-hex = "2.1.0"
substrate-bip39 = "0.4.0"
hex = "0.4.2"
hex-literal = "0.2.1"
codec = { package = "parity-scale-codec", version = "1.0.0" }
frame-system = { version = "2.0.0-alpha.3", git = "https://github.com/paritytech/substrate" }
pallet-balances = { version = "2.0.0-alpha.3", git = "https://github.com/paritytech/substrate" }
pallet-transaction-payment = { version = "2.0.0-alpha.3", git = "https://github.com/paritytech/substrate" }
rpassword = "4.0.5"
itertools = "0.9.0"
derive_more = "0.99.3"
sc-rpc = { version = "2.0.0-alpha.3", git = "https://github.com/paritytech/substrate" }
jsonrpc-core-client = { version = "14.0.5", features = ["http"] }
hyper = "0.13.3"

[features]
bench = []
